--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/gigi/.config/wpg/wallpapers/flamingowall.jpg"

-- Special
background="#091f2c"
foreground="#fefef7"
cursor="#fefef7"

-- Colors
color0="#091f2c"
color1="#d07c67"
color2="#617c42"
color3="#797543"
color4="#30a490"
color5="#ae7583"
color6="#488776"
color7="#ecccc2"
color8="#203a3e"
color9="#e6958b"
color10="#9CA259"
color11="#cac46e"
color12="#8abeb7"
color13="#bc94a3"
color14="#b2d5b7"
color15="#fefef7"
