# Shell variables
# Generated by 'wal'
wallpaper='/home/gigi/.config/wpg/wallpapers/flamingowall.jpg'

# Special
background='#091f2c'
foreground='#fefef7'
cursor='#fefef7'

# Colors
color0='#091f2c'
color1='#d07c67'
color2='#617c42'
color3='#797543'
color4='#30a490'
color5='#ae7583'
color6='#488776'
color7='#ecccc2'
color8='#203a3e'
color9='#e6958b'
color10='#9CA259'
color11='#cac46e'
color12='#8abeb7'
color13='#bc94a3'
color14='#b2d5b7'
color15='#fefef7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
