[Desktop Entry]
Name=dark-paradise
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=dark-paradise
MetacityTheme=dark-paradise
IconTheme=default
GtkColorScheme=base_color:#091f2c,fg_color:#e6958b,tooltip_fg_color:#e6958b,selected_bg_color:#cac46e,selected_fg_color:#000000,text_color:#e6958b,bg_color:#091f2c,tooltip_bg_color:#091f2c
CursorTheme=default
CursorSize=18
NotificationTheme=slider
